services:
  minecraft:
    restart: unless-stopped
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: PAPER
      VERSION: 1.19
    ports:
      - "25565:25565"
    volumes:
      - "/data/minecraft/server:/data"
  rcon:
    restart: unless-stopped
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: minecraft
      #RWA_RCON_PORT: 28016
      RWA_RCON_PASSWORD: minecraft
